"""Short repository-name reject terms for admission."""

REPO_NAME_REJECT_TERMS = (
    "arxiv",
    "paper",
    "papers",
    "review",
    "preprint",
    "bibliography",
    "reading",
    "tutorial",
    "tutorials",
    "lesson",
    "lessons",
    "lecture",
    "lectures",
    "thesis",
    "phd",
    "msc",
    "bsc",
    "slides",
    "course",
    "courses",
    "coursework",
    "homework",
    "notes",
    "syllabus",
)
