"""Path-match terms for admission."""

STRONG_PATH_SEGMENT_HINTS = (
    "src/",
    "lib/",
    "app/",
    "cmd/",
    "bin/",
    "include/",
    "bindings/",
    "module/",
    "modules/",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "requirements.txt",
    "environment.yml",
    "environment.yaml",
    "project.toml",
    "manifest.toml",
    "cargo.toml",
    "package.json",
    "cmakelists.txt",
    "meson.build",
    "sconstruct",
    "makefile",
)

STRONG_PATH_EXTENSIONS = (
    ".py",
    ".pyx",
    ".pxd",
    ".pxi",
    ".r",
    ".jl",
    ".f90",
    ".f95",
    ".f03",
    ".f08",
    ".f",
    ".c",
    ".cc",
    ".hh",
    ".cpp",
    ".cxx",
    ".cu",
    ".cuh",
    ".h",
    ".hpp",
    ".rs",
    ".go",
    ".java",
    ".kt",
    ".m",
    ".mm",
    ".scala",
    ".sh",
    ".tcc",
)

DESCRIPTIVE_PATH_HINTS = (
    "readme",
    "docs/",
    "doc/",
    "examples/",
    "example/",
    "tutorial/",
    "tutorials/",
    "notebook/",
    "notebooks/",
)

DESCRIPTIVE_PATH_EXTENSIONS = (".md", ".rst", ".txt", ".ipynb")

WEAK_PATH_HINTS = (
    "tests/",
    "test/",
    "unittest/",
    "fixtures/",
    "fixture/",
    "mock/",
    "mocks/",
    "spec/",
    "specs/",
    "bench/",
)
